### ISSUE TITLE
Field Set API Name for Managed Fields

### ISSUE THREAD

**Issue by mattsimonis** [mattsimonis/boostr#15]
The API name that shows up for managed package fields is the ID of the field, and not the API name.

**Comment by DavidCDean** [comment]
Hey Matt. I see where the fieldset json has ID's instead of API names. It looks like the troughData section might contain all the matching api names instead. 

Edit: Nevermind... just looked. Appears you're parsing it off the containing element's ID. I don't see the actual API names anywhere in the tree, there... maybe it's worth exploring the bit I mentioned above?

**Comment by mattsimonis** [comment]
@DavidCDean Biggest hurdle is that Chrome extensions do not have access to the window and variables defined there (for security reasons). I'll look into injecting the field set script into the page so that it has access to that data and can then use it to get the name from the id of the element. I have a working prototype right now of this locally and will try to optimize it more.
