### ISSUE TITLE
Field History Tracking Counter doesn't take limit increases into account

### ISSUE THREAD

**Issue by jneavesf** [mattsimonis/boostr#39]
The "Field History Tracking Counter" (eg. "11 of 20 selected" when setting field history tracking) doesn't take into account any limit increases that have been applied to the org. Salesforce can increase the field history limit per object beyond 20, and Boostr doesn't take these into account. It always displays a maximum of 20.

**Comment by mattsimonis** [comment]
@jneavesf - Unfortunately Salesforce doesn't provide an API to gather information about what the field history tracking limit is per object (or at least I couldn't find anything after searching for a while). If you know of a way to get this information (aside from when you save the record and get an error), I could look into adding that functionality.

**Comment by lfreeland** [comment]
@mattsimonis, It stinks that Salesforce doesn't have an API to easily determine what the limit is automatically. However, the next best thing is to make it configurable so that's what I did with this [pull request](https://github.com/mattsimonis/boostr/pull/41).

I hope this helps, @jneavesf.

Happy Coding,
Luke

**Comment by lfreeland** [comment]
@jneavesf, This is now in the latest release. Open the options and put in the number of allowed history tracking fields for your org. Cheers!

**Comment by jneavesf** [comment]
that is perfect @lfreeland and @mattsimonis - I appreciate you adding this.
